{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Importar librería para la conexión con MySQL\n",
    "# -----------------------------------------------------------------------\n",
    "import mysql.connector\n",
    "from mysql.connector import errorcode\n",
    "\n",
    "\n",
    "# Importar librerías para manipulación y análisis de datos\n",
    "# -----------------------------------------------------------------------\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "MySQLCursor: CREATE DATABASE IF NOT EXISTS CineParadi..\n"
     ]
    }
   ],
   "source": [
    "cnx = mysql.connector.connect(\n",
    "    user=\"root\",\n",
    "    password=\"AlumnaAdalab\",\n",
    "    host=\"127.0.0.1\",\n",
    "    auth_plugin='mysql_native_password'\n",
    ")\n",
    "\n",
    "mycursor = cnx.cursor()\n",
    "\n",
    "try:\n",
    "    mycursor.execute(\"CREATE DATABASE IF NOT EXISTS CineParadiso\")\n",
    "    print(mycursor)\n",
    "\n",
    "except mysql.connector.Error as err:\n",
    "    print(err)\n",
    "    print(\"Error code:\", err.errno)\n",
    "    print(\"SOLSTATE\", err.sqlstate)\n",
    "    print(\"Message\", err.msg)\n",
    "    \n",
    "cnx.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1050 (42S01): Table 'film' already exists\n",
      "Error Code: 1050\n",
      "SQLSTATE 42S01\n",
      "Message Table 'film' already exists\n"
     ]
    }
   ],
   "source": [
    "# Tabla FILM\n",
    "\n",
    "cnx = mysql.connector.connect(\n",
    "    user=\"root\",\n",
    "    password=\"AlumnaAdalab\",\n",
    "    host=\"127.0.0.1\",\n",
    "    database=\"CineParadiso\",\n",
    "    auth_plugin='mysql_native_password'\n",
    ")\n",
    "\n",
    "mycursor = cnx.cursor()\n",
    "\n",
    "query = \"CREATE TABLE film (film_id INT AUTO_INCREMENT PRIMARY KEY, idOwner VARCHAR (30), title VARCHAR (100), type VARCHAR (30), year VARCHAR (10), genre VARCHAR (30), screenwriter VARCHAR (50), management VARCHAR (50), plot VARCHAR (1000), length INT, rating VARCHAR (10))\"\n",
    "\n",
    "try:\n",
    "    mycursor.execute(query)\n",
    "\n",
    "    print(mycursor)\n",
    "    \n",
    "except mysql.connector.Error as err:\n",
    "    print(err)\n",
    "    print(\"Error Code:\", err.errno)\n",
    "    print(\"SQLSTATE\", err.sqlstate)\n",
    "    print(\"Message\", err.msg)\n",
    "    \n",
    "cnx.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1050 (42S01): Table 'cast' already exists\n",
      "Error Code: 1050\n",
      "SQLSTATE 42S01\n",
      "Message Table 'cast' already exists\n"
     ]
    }
   ],
   "source": [
    "# Tabla CAST\n",
    "\n",
    "cnx = mysql.connector.connect(\n",
    "    user=\"root\",\n",
    "    password=\"AlumnaAdalab\",\n",
    "    host=\"127.0.0.1\",\n",
    "    database=\"CineParadiso\",\n",
    "    auth_plugin='mysql_native_password'\n",
    ")\n",
    "\n",
    "mycursor = cnx.cursor()\n",
    "\n",
    "\n",
    "query = \"CREATE TABLE cast (cast_id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR (50), birth VARCHAR (30), award VARCHAR (500), nomination VARCHAR (500), known_for VARCHAR (500))\"\n",
    "\n",
    "try:\n",
    "    mycursor.execute(query)\n",
    "\n",
    "    print(mycursor)\n",
    "    \n",
    "except mysql.connector.Error as err:\n",
    "    print(err)\n",
    "    print(\"Error Code:\", err.errno)\n",
    "    print(\"SQLSTATE\", err.sqlstate)\n",
    "    print(\"Message\", err.msg)\n",
    "    \n",
    "cnx.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1050 (42S01): Table 'oscars' already exists\n",
      "Error Code: 1050\n",
      "SQLSTATE 42S01\n",
      "Message Table 'oscars' already exists\n"
     ]
    }
   ],
   "source": [
    "# Tabla OSCARS\n",
    "\n",
    "cnx = mysql.connector.connect(\n",
    "    user=\"root\",\n",
    "    password=\"AlumnaAdalab\",\n",
    "    host=\"127.0.0.1\",\n",
    "    database=\"CineParadiso\",\n",
    "    auth_plugin='mysql_native_password'\n",
    ")\n",
    "\n",
    "mycursor = cnx.cursor()\n",
    "\n",
    "\n",
    "query = \"CREATE TABLE oscars (oscar_id INT AUTO_INCREMENT PRIMARY KEY, date VARCHAR (30), best_film VARCHAR (50), best_management VARCHAR (40), best_actor VARCHAR (40), best_actress VARCHAR (40))\"\n",
    "\n",
    "try:\n",
    "    mycursor.execute(query)\n",
    "\n",
    "    print(mycursor)\n",
    "    \n",
    "except mysql.connector.Error as err:\n",
    "    print(err)\n",
    "    print(\"Error Code:\", err.errno)\n",
    "    print(\"SQLSTATE\", err.sqlstate)\n",
    "    print(\"Message\", err.msg)\n",
    "    \n",
    "cnx.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1050 (42S01): Table 'film_cast_oscars' already exists\n",
      "Error Code: 1050\n",
      "SQLSTATE 42S01\n",
      "Message Table 'film_cast_oscars' already exists\n"
     ]
    }
   ],
   "source": [
    "# Tabla FILM_CAST_OSCARS\n",
    "\n",
    "cnx = mysql.connector.connect(\n",
    "    user=\"root\",\n",
    "    password=\"AlumnaAdalab\",\n",
    "    host=\"127.0.0.1\",\n",
    "    database=\"CineParadiso\",\n",
    "    auth_plugin='mysql_native_password'\n",
    ")\n",
    "\n",
    "mycursor = cnx.cursor()\n",
    "\n",
    "\n",
    "query = (\"\"\"\n",
    "         CREATE TABLE film_cast_oscars (\n",
    "    id_film_cast_oscars INT AUTO_INCREMENT PRIMARY KEY,\n",
    "    film_id INT,\n",
    "    cast_id INT,\n",
    "    oscar_id INT,\n",
    "    FOREIGN KEY (film_id) REFERENCES film(film_id),\n",
    "    FOREIGN KEY (cast_id) REFERENCES `cast`(cast_id),\n",
    "    FOREIGN KEY (oscar_id) REFERENCES oscars(oscar_id));\n",
    "    \"\"\")\n",
    "\n",
    "\n",
    "try:\n",
    "    mycursor.execute(query)\n",
    "\n",
    "    print(mycursor)\n",
    "    \n",
    "except mysql.connector.Error as err:\n",
    "    print(err)\n",
    "    print(\"Error Code:\", err.errno)\n",
    "    print(\"SQLSTATE\", err.sqlstate)\n",
    "    print(\"Message\", err.msg)\n",
    "    \n",
    "cnx.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "ename": "FileNotFoundError",
     "evalue": "[Errno 2] No such file or directory: 'Oscars.csv'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[31], line 13\u001b[0m\n\u001b[0;32m      9\u001b[0m mycursor \u001b[38;5;241m=\u001b[39m cnx\u001b[38;5;241m.\u001b[39mcursor()\n\u001b[0;32m     11\u001b[0m \u001b[38;5;66;03m## Leer el CSV donde tengo la info:\u001b[39;00m\n\u001b[1;32m---> 13\u001b[0m data_movies \u001b[38;5;241m=\u001b[39m \u001b[43mpd\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mread_csv\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mOscars.csv\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[0;32m     16\u001b[0m query \u001b[38;5;241m=\u001b[39m (\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mINSERT INTO Oscars (date, best_film, best_management, best_actor, best_actress) VALUES (\u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m,\u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m,\u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m,\u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m,\u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m)\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m     19\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m _, row \u001b[38;5;129;01min\u001b[39;00m data_movies\u001b[38;5;241m.\u001b[39miterrows():\n",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\io\\parsers\\readers.py:1026\u001b[0m, in \u001b[0;36mread_csv\u001b[1;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)\u001b[0m\n\u001b[0;32m   1013\u001b[0m kwds_defaults \u001b[38;5;241m=\u001b[39m _refine_defaults_read(\n\u001b[0;32m   1014\u001b[0m     dialect,\n\u001b[0;32m   1015\u001b[0m     delimiter,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   1022\u001b[0m     dtype_backend\u001b[38;5;241m=\u001b[39mdtype_backend,\n\u001b[0;32m   1023\u001b[0m )\n\u001b[0;32m   1024\u001b[0m kwds\u001b[38;5;241m.\u001b[39mupdate(kwds_defaults)\n\u001b[1;32m-> 1026\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43m_read\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfilepath_or_buffer\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mkwds\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\io\\parsers\\readers.py:620\u001b[0m, in \u001b[0;36m_read\u001b[1;34m(filepath_or_buffer, kwds)\u001b[0m\n\u001b[0;32m    617\u001b[0m _validate_names(kwds\u001b[38;5;241m.\u001b[39mget(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mnames\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;28;01mNone\u001b[39;00m))\n\u001b[0;32m    619\u001b[0m \u001b[38;5;66;03m# Create the parser.\u001b[39;00m\n\u001b[1;32m--> 620\u001b[0m parser \u001b[38;5;241m=\u001b[39m \u001b[43mTextFileReader\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfilepath_or_buffer\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwds\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    622\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m chunksize \u001b[38;5;129;01mor\u001b[39;00m iterator:\n\u001b[0;32m    623\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m parser\n",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\io\\parsers\\readers.py:1620\u001b[0m, in \u001b[0;36mTextFileReader.__init__\u001b[1;34m(self, f, engine, **kwds)\u001b[0m\n\u001b[0;32m   1617\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39moptions[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhas_index_names\u001b[39m\u001b[38;5;124m\"\u001b[39m] \u001b[38;5;241m=\u001b[39m kwds[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhas_index_names\u001b[39m\u001b[38;5;124m\"\u001b[39m]\n\u001b[0;32m   1619\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mhandles: IOHandles \u001b[38;5;241m|\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m-> 1620\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_engine \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_make_engine\u001b[49m\u001b[43m(\u001b[49m\u001b[43mf\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mengine\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\io\\parsers\\readers.py:1880\u001b[0m, in \u001b[0;36mTextFileReader._make_engine\u001b[1;34m(self, f, engine)\u001b[0m\n\u001b[0;32m   1878\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mb\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;129;01min\u001b[39;00m mode:\n\u001b[0;32m   1879\u001b[0m         mode \u001b[38;5;241m+\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mb\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m-> 1880\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mhandles \u001b[38;5;241m=\u001b[39m \u001b[43mget_handle\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m   1881\u001b[0m \u001b[43m    \u001b[49m\u001b[43mf\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m   1882\u001b[0m \u001b[43m    \u001b[49m\u001b[43mmode\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m   1883\u001b[0m \u001b[43m    \u001b[49m\u001b[43mencoding\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43moptions\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mencoding\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mNone\u001b[39;49;00m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m   1884\u001b[0m \u001b[43m    \u001b[49m\u001b[43mcompression\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43moptions\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mcompression\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mNone\u001b[39;49;00m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m   1885\u001b[0m \u001b[43m    \u001b[49m\u001b[43mmemory_map\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43moptions\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mmemory_map\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m   1886\u001b[0m \u001b[43m    \u001b[49m\u001b[43mis_text\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mis_text\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m   1887\u001b[0m \u001b[43m    \u001b[49m\u001b[43merrors\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43moptions\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mencoding_errors\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mstrict\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m   1888\u001b[0m \u001b[43m    \u001b[49m\u001b[43mstorage_options\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43moptions\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mstorage_options\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mNone\u001b[39;49;00m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m   1889\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   1890\u001b[0m \u001b[38;5;28;01massert\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mhandles \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[0;32m   1891\u001b[0m f \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mhandles\u001b[38;5;241m.\u001b[39mhandle\n",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\io\\common.py:873\u001b[0m, in \u001b[0;36mget_handle\u001b[1;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)\u001b[0m\n\u001b[0;32m    868\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(handle, \u001b[38;5;28mstr\u001b[39m):\n\u001b[0;32m    869\u001b[0m     \u001b[38;5;66;03m# Check whether the filename is to be opened in binary mode.\u001b[39;00m\n\u001b[0;32m    870\u001b[0m     \u001b[38;5;66;03m# Binary mode does not support 'encoding' and 'newline'.\u001b[39;00m\n\u001b[0;32m    871\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m ioargs\u001b[38;5;241m.\u001b[39mencoding \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mb\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;129;01min\u001b[39;00m ioargs\u001b[38;5;241m.\u001b[39mmode:\n\u001b[0;32m    872\u001b[0m         \u001b[38;5;66;03m# Encoding\u001b[39;00m\n\u001b[1;32m--> 873\u001b[0m         handle \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mopen\u001b[39;49m\u001b[43m(\u001b[49m\n\u001b[0;32m    874\u001b[0m \u001b[43m            \u001b[49m\u001b[43mhandle\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    875\u001b[0m \u001b[43m            \u001b[49m\u001b[43mioargs\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmode\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    876\u001b[0m \u001b[43m            \u001b[49m\u001b[43mencoding\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mioargs\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mencoding\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    877\u001b[0m \u001b[43m            \u001b[49m\u001b[43merrors\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43merrors\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    878\u001b[0m \u001b[43m            \u001b[49m\u001b[43mnewline\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m    879\u001b[0m \u001b[43m        \u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    880\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    881\u001b[0m         \u001b[38;5;66;03m# Binary mode\u001b[39;00m\n\u001b[0;32m    882\u001b[0m         handle \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mopen\u001b[39m(handle, ioargs\u001b[38;5;241m.\u001b[39mmode)\n",
      "\u001b[1;31mFileNotFoundError\u001b[0m: [Errno 2] No such file or directory: 'Oscars.csv'"
     ]
    }
   ],
   "source": [
    "\n",
    "cnx = mysql.connector.connect(\n",
    "    user=\"root\",\n",
    "    password=\"AlumnaAdalab\",\n",
    "    host=\"127.0.0.1\",\n",
    "    database=\"CineParadiso\",\n",
    "    auth_plugin='mysql_native_password'\n",
    ")\n",
    "\n",
    "mycursor = cnx.cursor()\n",
    "\n",
    "## Leer el CSV donde tengo la info:\n",
    "\n",
    "data_movies = pd.read_csv('Oscars.csv')\n",
    "\n",
    "\n",
    "query = ('INSERT INTO Oscars (date, best_film, best_management, best_actor, best_actress) VALUES (%s,%s,%s,%s,%s)')\n",
    "\n",
    "\n",
    "for _, row in data_movies.iterrows():\n",
    "    \n",
    "    try:\n",
    "        mycursor.execute(query, tuple(row))\n",
    "    \n",
    "    except mysql.connector.Error as err:\n",
    "        print(f'Error insertando fila {row['id']}: {err}')\n",
    "        \n",
    "## Confirmar los cambios en la base de datos\n",
    "\n",
    "cnx.commit()\n",
    "\n",
    "## Cerrar el cursor y la conexión\n",
    "\n",
    "mycursor.close()\n",
    "cnx.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "'id'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mProgrammingError\u001b[0m                          Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[23], line 22\u001b[0m\n\u001b[0;32m     21\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 22\u001b[0m     \u001b[43mmycursor\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexecute\u001b[49m\u001b[43m(\u001b[49m\u001b[43mquery\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mtuple\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mrow\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     24\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m mysql\u001b[38;5;241m.\u001b[39mconnector\u001b[38;5;241m.\u001b[39mError \u001b[38;5;28;01mas\u001b[39;00m err:\n",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\mysql\\connector\\cursor.py:551\u001b[0m, in \u001b[0;36mMySQLCursor.execute\u001b[1;34m(self, operation, params, multi)\u001b[0m\n\u001b[0;32m    550\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 551\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_handle_result(\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_connection\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcmd_query\u001b[49m\u001b[43m(\u001b[49m\u001b[43mstmt\u001b[49m\u001b[43m)\u001b[49m)\n\u001b[0;32m    552\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m errors\u001b[38;5;241m.\u001b[39mInterfaceError:\n",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\mysql\\connector\\connection.py:490\u001b[0m, in \u001b[0;36mMySQLConnection.cmd_query\u001b[1;34m(self, query, raw, buffered, raw_as_string)\u001b[0m\n\u001b[0;32m    489\u001b[0m     query \u001b[38;5;241m=\u001b[39m query\u001b[38;5;241m.\u001b[39mencode(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mutf-8\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[1;32m--> 490\u001b[0m result \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_handle_result\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_send_cmd\u001b[49m\u001b[43m(\u001b[49m\u001b[43mServerCmd\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mQUERY\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mquery\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    492\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_have_next_result:\n",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\mysql\\connector\\connection.py:395\u001b[0m, in \u001b[0;36mMySQLConnection._handle_result\u001b[1;34m(self, packet)\u001b[0m\n\u001b[0;32m    394\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m packet[\u001b[38;5;241m4\u001b[39m] \u001b[38;5;241m==\u001b[39m \u001b[38;5;241m255\u001b[39m:\n\u001b[1;32m--> 395\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m errors\u001b[38;5;241m.\u001b[39mget_exception(packet)\n\u001b[0;32m    397\u001b[0m \u001b[38;5;66;03m# We have a text result set\u001b[39;00m\n",
      "\u001b[1;31mProgrammingError\u001b[0m: 1054 (42S22): Unknown column 'nan' in 'field list'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\indexes\\base.py:3805\u001b[0m, in \u001b[0;36mIndex.get_loc\u001b[1;34m(self, key)\u001b[0m\n\u001b[0;32m   3804\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m-> 3805\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_engine\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_loc\u001b[49m\u001b[43m(\u001b[49m\u001b[43mcasted_key\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   3806\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mKeyError\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m err:\n",
      "File \u001b[1;32mindex.pyx:167\u001b[0m, in \u001b[0;36mpandas._libs.index.IndexEngine.get_loc\u001b[1;34m()\u001b[0m\n",
      "File \u001b[1;32mindex.pyx:196\u001b[0m, in \u001b[0;36mpandas._libs.index.IndexEngine.get_loc\u001b[1;34m()\u001b[0m\n",
      "File \u001b[1;32mpandas\\\\_libs\\\\hashtable_class_helper.pxi:7081\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.get_item\u001b[1;34m()\u001b[0m\n",
      "File \u001b[1;32mpandas\\\\_libs\\\\hashtable_class_helper.pxi:7089\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.get_item\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mKeyError\u001b[0m: 'id'",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[1;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[23], line 25\u001b[0m\n\u001b[0;32m     22\u001b[0m         mycursor\u001b[38;5;241m.\u001b[39mexecute(query, \u001b[38;5;28mtuple\u001b[39m(row))\n\u001b[0;32m     24\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m mysql\u001b[38;5;241m.\u001b[39mconnector\u001b[38;5;241m.\u001b[39mError \u001b[38;5;28;01mas\u001b[39;00m err:\n\u001b[1;32m---> 25\u001b[0m         \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mError insertando fila \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[43mrow\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mid\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00merr\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m     27\u001b[0m \u001b[38;5;66;03m## Confirmar los cambios en la base de datos\u001b[39;00m\n\u001b[0;32m     29\u001b[0m cnx\u001b[38;5;241m.\u001b[39mcommit()\n",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\series.py:1121\u001b[0m, in \u001b[0;36mSeries.__getitem__\u001b[1;34m(self, key)\u001b[0m\n\u001b[0;32m   1118\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_values[key]\n\u001b[0;32m   1120\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m key_is_scalar:\n\u001b[1;32m-> 1121\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_get_value\u001b[49m\u001b[43m(\u001b[49m\u001b[43mkey\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   1123\u001b[0m \u001b[38;5;66;03m# Convert generator to list before going through hashable part\u001b[39;00m\n\u001b[0;32m   1124\u001b[0m \u001b[38;5;66;03m# (We will iterate through the generator there to check for slices)\u001b[39;00m\n\u001b[0;32m   1125\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m is_iterator(key):\n",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\series.py:1237\u001b[0m, in \u001b[0;36mSeries._get_value\u001b[1;34m(self, label, takeable)\u001b[0m\n\u001b[0;32m   1234\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_values[label]\n\u001b[0;32m   1236\u001b[0m \u001b[38;5;66;03m# Similar to Index.get_value, but we do not fall back to positional\u001b[39;00m\n\u001b[1;32m-> 1237\u001b[0m loc \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mindex\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_loc\u001b[49m\u001b[43m(\u001b[49m\u001b[43mlabel\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   1239\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m is_integer(loc):\n\u001b[0;32m   1240\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_values[loc]\n",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\indexes\\base.py:3812\u001b[0m, in \u001b[0;36mIndex.get_loc\u001b[1;34m(self, key)\u001b[0m\n\u001b[0;32m   3807\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(casted_key, \u001b[38;5;28mslice\u001b[39m) \u001b[38;5;129;01mor\u001b[39;00m (\n\u001b[0;32m   3808\u001b[0m         \u001b[38;5;28misinstance\u001b[39m(casted_key, abc\u001b[38;5;241m.\u001b[39mIterable)\n\u001b[0;32m   3809\u001b[0m         \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;28many\u001b[39m(\u001b[38;5;28misinstance\u001b[39m(x, \u001b[38;5;28mslice\u001b[39m) \u001b[38;5;28;01mfor\u001b[39;00m x \u001b[38;5;129;01min\u001b[39;00m casted_key)\n\u001b[0;32m   3810\u001b[0m     ):\n\u001b[0;32m   3811\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m InvalidIndexError(key)\n\u001b[1;32m-> 3812\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mKeyError\u001b[39;00m(key) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01merr\u001b[39;00m\n\u001b[0;32m   3813\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m:\n\u001b[0;32m   3814\u001b[0m     \u001b[38;5;66;03m# If we have a listlike key, _check_indexing_error will raise\u001b[39;00m\n\u001b[0;32m   3815\u001b[0m     \u001b[38;5;66;03m#  InvalidIndexError. Otherwise we fall through and re-raise\u001b[39;00m\n\u001b[0;32m   3816\u001b[0m     \u001b[38;5;66;03m#  the TypeError.\u001b[39;00m\n\u001b[0;32m   3817\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_check_indexing_error(key)\n",
      "\u001b[1;31mKeyError\u001b[0m: 'id'"
     ]
    }
   ],
   "source": [
    "cnx = mysql.connector.connect(\n",
    "    user=\"root\",\n",
    "    password=\"AlumnaAdalab\",\n",
    "    host=\"127.0.0.1\",\n",
    "    database=\"CineParadiso\",\n",
    "    auth_plugin='mysql_native_password'\n",
    ")\n",
    "\n",
    "mycursor = cnx.cursor()\n",
    "\n",
    "## Leer el CSV donde tengo la info:\n",
    "\n",
    "data_movies = pd.read_csv('FilmsCompleto.csv')\n",
    "\n",
    "\n",
    "query = ('INSERT INTO Film (idOwner, title, type, year, genre, screenwriter, management, plot, length, rating) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)')\n",
    "\n",
    "\n",
    "for _, row in data_movies.iterrows():\n",
    "    \n",
    "    try:\n",
    "        mycursor.execute(query, tuple(row))\n",
    "    \n",
    "    except mysql.connector.Error as err:\n",
    "        print(f'Error insertando fila {row['id']}: {err}')\n",
    "        \n",
    "## Confirmar los cambios en la base de datos\n",
    "\n",
    "cnx.commit()\n",
    "\n",
    "## Cerrar el cursor y la conexión\n",
    "\n",
    "mycursor.close()\n",
    "cnx.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "'id'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mProgrammingError\u001b[0m                          Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[24], line 24\u001b[0m\n\u001b[0;32m     23\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 24\u001b[0m     \u001b[43mmycursor\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexecute\u001b[49m\u001b[43m(\u001b[49m\u001b[43mquery\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mtuple\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mrow\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     25\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m mysql\u001b[38;5;241m.\u001b[39mconnector\u001b[38;5;241m.\u001b[39mError \u001b[38;5;28;01mas\u001b[39;00m err:\n",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\mysql\\connector\\cursor.py:551\u001b[0m, in \u001b[0;36mMySQLCursor.execute\u001b[1;34m(self, operation, params, multi)\u001b[0m\n\u001b[0;32m    550\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 551\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_handle_result(\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_connection\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcmd_query\u001b[49m\u001b[43m(\u001b[49m\u001b[43mstmt\u001b[49m\u001b[43m)\u001b[49m)\n\u001b[0;32m    552\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m errors\u001b[38;5;241m.\u001b[39mInterfaceError:\n",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\mysql\\connector\\connection.py:490\u001b[0m, in \u001b[0;36mMySQLConnection.cmd_query\u001b[1;34m(self, query, raw, buffered, raw_as_string)\u001b[0m\n\u001b[0;32m    489\u001b[0m     query \u001b[38;5;241m=\u001b[39m query\u001b[38;5;241m.\u001b[39mencode(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mutf-8\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[1;32m--> 490\u001b[0m result \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_handle_result\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_send_cmd\u001b[49m\u001b[43m(\u001b[49m\u001b[43mServerCmd\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mQUERY\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mquery\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    492\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_have_next_result:\n",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\mysql\\connector\\connection.py:395\u001b[0m, in \u001b[0;36mMySQLConnection._handle_result\u001b[1;34m(self, packet)\u001b[0m\n\u001b[0;32m    394\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m packet[\u001b[38;5;241m4\u001b[39m] \u001b[38;5;241m==\u001b[39m \u001b[38;5;241m255\u001b[39m:\n\u001b[1;32m--> 395\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m errors\u001b[38;5;241m.\u001b[39mget_exception(packet)\n\u001b[0;32m    397\u001b[0m \u001b[38;5;66;03m# We have a text result set\u001b[39;00m\n",
      "\u001b[1;31mProgrammingError\u001b[0m: 1054 (42S22): Unknown column 'nan' in 'field list'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\indexes\\base.py:3805\u001b[0m, in \u001b[0;36mIndex.get_loc\u001b[1;34m(self, key)\u001b[0m\n\u001b[0;32m   3804\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m-> 3805\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_engine\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_loc\u001b[49m\u001b[43m(\u001b[49m\u001b[43mcasted_key\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   3806\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mKeyError\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m err:\n",
      "File \u001b[1;32mindex.pyx:167\u001b[0m, in \u001b[0;36mpandas._libs.index.IndexEngine.get_loc\u001b[1;34m()\u001b[0m\n",
      "File \u001b[1;32mindex.pyx:196\u001b[0m, in \u001b[0;36mpandas._libs.index.IndexEngine.get_loc\u001b[1;34m()\u001b[0m\n",
      "File \u001b[1;32mpandas\\\\_libs\\\\hashtable_class_helper.pxi:7081\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.get_item\u001b[1;34m()\u001b[0m\n",
      "File \u001b[1;32mpandas\\\\_libs\\\\hashtable_class_helper.pxi:7089\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.get_item\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mKeyError\u001b[0m: 'id'",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[1;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[24], line 26\u001b[0m\n\u001b[0;32m     24\u001b[0m         mycursor\u001b[38;5;241m.\u001b[39mexecute(query, \u001b[38;5;28mtuple\u001b[39m(row))\n\u001b[0;32m     25\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m mysql\u001b[38;5;241m.\u001b[39mconnector\u001b[38;5;241m.\u001b[39mError \u001b[38;5;28;01mas\u001b[39;00m err:\n\u001b[1;32m---> 26\u001b[0m         \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mError insertando fila \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[43mrow\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mid\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00merr\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m     28\u001b[0m \u001b[38;5;66;03m# Confirmar los cambios en la base de datos\u001b[39;00m\n\u001b[0;32m     29\u001b[0m cnx\u001b[38;5;241m.\u001b[39mcommit()\n",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\series.py:1121\u001b[0m, in \u001b[0;36mSeries.__getitem__\u001b[1;34m(self, key)\u001b[0m\n\u001b[0;32m   1118\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_values[key]\n\u001b[0;32m   1120\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m key_is_scalar:\n\u001b[1;32m-> 1121\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_get_value\u001b[49m\u001b[43m(\u001b[49m\u001b[43mkey\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   1123\u001b[0m \u001b[38;5;66;03m# Convert generator to list before going through hashable part\u001b[39;00m\n\u001b[0;32m   1124\u001b[0m \u001b[38;5;66;03m# (We will iterate through the generator there to check for slices)\u001b[39;00m\n\u001b[0;32m   1125\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m is_iterator(key):\n",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\series.py:1237\u001b[0m, in \u001b[0;36mSeries._get_value\u001b[1;34m(self, label, takeable)\u001b[0m\n\u001b[0;32m   1234\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_values[label]\n\u001b[0;32m   1236\u001b[0m \u001b[38;5;66;03m# Similar to Index.get_value, but we do not fall back to positional\u001b[39;00m\n\u001b[1;32m-> 1237\u001b[0m loc \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mindex\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_loc\u001b[49m\u001b[43m(\u001b[49m\u001b[43mlabel\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   1239\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m is_integer(loc):\n\u001b[0;32m   1240\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_values[loc]\n",
      "File \u001b[1;32mc:\\Users\\leyre\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\indexes\\base.py:3812\u001b[0m, in \u001b[0;36mIndex.get_loc\u001b[1;34m(self, key)\u001b[0m\n\u001b[0;32m   3807\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(casted_key, \u001b[38;5;28mslice\u001b[39m) \u001b[38;5;129;01mor\u001b[39;00m (\n\u001b[0;32m   3808\u001b[0m         \u001b[38;5;28misinstance\u001b[39m(casted_key, abc\u001b[38;5;241m.\u001b[39mIterable)\n\u001b[0;32m   3809\u001b[0m         \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;28many\u001b[39m(\u001b[38;5;28misinstance\u001b[39m(x, \u001b[38;5;28mslice\u001b[39m) \u001b[38;5;28;01mfor\u001b[39;00m x \u001b[38;5;129;01min\u001b[39;00m casted_key)\n\u001b[0;32m   3810\u001b[0m     ):\n\u001b[0;32m   3811\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m InvalidIndexError(key)\n\u001b[1;32m-> 3812\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mKeyError\u001b[39;00m(key) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01merr\u001b[39;00m\n\u001b[0;32m   3813\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m:\n\u001b[0;32m   3814\u001b[0m     \u001b[38;5;66;03m# If we have a listlike key, _check_indexing_error will raise\u001b[39;00m\n\u001b[0;32m   3815\u001b[0m     \u001b[38;5;66;03m#  InvalidIndexError. Otherwise we fall through and re-raise\u001b[39;00m\n\u001b[0;32m   3816\u001b[0m     \u001b[38;5;66;03m#  the TypeError.\u001b[39;00m\n\u001b[0;32m   3817\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_check_indexing_error(key)\n",
      "\u001b[1;31mKeyError\u001b[0m: 'id'"
     ]
    }
   ],
   "source": [
    "import mysql.connector\n",
    "import pandas as pd\n",
    "\n",
    "# Conexión a la base de datos\n",
    "cnx = mysql.connector.connect(\n",
    "    user=\"root\",\n",
    "    password=\"AlumnaAdalab\",\n",
    "    host=\"127.0.0.1\",\n",
    "    database=\"CineParadiso\",\n",
    "    auth_plugin='mysql_native_password'\n",
    ")\n",
    "\n",
    "mycursor = cnx.cursor()\n",
    "\n",
    "# Leer el CSV donde tienes la información\n",
    "data_movies = pd.read_csv('FilmsCompleto.csv')\n",
    "\n",
    "# Definir la consulta de inserción\n",
    "query = ('INSERT INTO Film (idOwner, title, type, year, genre, screenwriter, management, plot, length, rating) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)')\n",
    "\n",
    "# Iterar sobre cada fila del DataFrame e insertar en la base de datos\n",
    "for _, row in data_movies.iterrows():\n",
    "    try:\n",
    "        mycursor.execute(query, tuple(row))\n",
    "    except mysql.connector.Error as err:\n",
    "        print(f\"Error insertando fila {row['id']}: {err}\")\n",
    "\n",
    "# Confirmar los cambios en la base de datos\n",
    "cnx.commit()\n",
    "\n",
    "# Cerrar el cursor y la conexión\n",
    "mycursor.close()\n",
    "cnx.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "     idOwner                       Title   Type    Year   Genre  \\\n",
      "0  tt0077634  The Great Skycopter Rescue  Movie  1980.0  Action   \n",
      "1  tt0076709                  Si wang ta  Movie  1980.0  Action   \n",
      "2  tt0078428         Shao Lin yu Wu Dang  Movie  1980.0  Action   \n",
      "3  tt0077645               Mie jue qi qi  Movie  1980.0  Action   \n",
      "4  tt0079106      L'empreinte des géants  Movie  1980.0  Action   \n",
      "\n",
      "                                 guionista  \\\n",
      "0  ('Donald G. Jackson', 'Randall Frakes')   \n",
      "1                        ('Siu-Jun Wong',)   \n",
      "2                        ('Anthony Jesu',)   \n",
      "3                     ('Robert Chappell',)   \n",
      "4   ('Charles B. Griffith', 'Lance Smith')   \n",
      "\n",
      "                                       direccion  \\\n",
      "0  ('Paul Donovan', 'Digby Cook', 'Tony Randel')   \n",
      "1                                   Terence Hill   \n",
      "2                                       Bong Luk   \n",
      "3                              Cirio H. Santiago   \n",
      "4                                     Cheh Chang   \n",
      "\n",
      "                                            sinopsis  duracion(minutos)  \\\n",
      "0  Two men and a woman circle the globe in a sate...               88.0   \n",
      "1  A priest helps the small town he's stationed i...              126.0   \n",
      "2  The 1990 Hong Kong action classic, starring Yu...               91.0   \n",
      "3  Una despiadada banda de vehículos domina el pá...               85.0   \n",
      "4  1936, the Japanese are allied with the Kuomint...               78.0   \n",
      "\n",
      "  nota imdb  \n",
      "0       4,5  \n",
      "1       5,6  \n",
      "2       5,8  \n",
      "3       4,1  \n",
      "4       6,4  \n",
      "Error insertando fila tt0078918: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080441: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0082532: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0084836: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0083061: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0085454: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0084738: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0086566: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0066151: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0088962: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0093663: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0092531: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0092926: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0099793: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0078411: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0079720: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0082788: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0083592: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0082469: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0085860: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0086595: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0087560: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0066020: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0086025: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0086028: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0085708: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0086964: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0089280: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0092503: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0080755: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0094735: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0095840: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0098965: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0101644: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0103770: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0075859: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0075631: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0076043: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0076321: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0076276: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0077366: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0062181: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0067100: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0075187: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0077389: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0076769: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0077472: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0077960: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0078376: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0077722: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0078769: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0078178: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0079358: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0079891: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0079799: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080508: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080554: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0036606: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0057461: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0065530: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0077329: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0079246: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080867: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080824: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0082578: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0071261: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080570: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0081716: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0082972: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0083969: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0084384: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0084388: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0082491: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0083852: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0075745: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0084324: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085155: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085185: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085309: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0067625: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0086021: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085986: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0086909: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0087210: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0087944: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0067694: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0076900: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0084549: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0084460: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085916: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0086584: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0086836: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0072818: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0082668: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0088274: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0090292: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0065108: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0083731: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0084548: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0087374: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0088900: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0089996: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0089382: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0091234: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0059325: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0059900: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0065188: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0068494: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0075259: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0081721: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0090665: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0093646: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0077432: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0084015: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0092507: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0094841: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0094900: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0095111: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0082891: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0084447: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0095761: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0096222: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0097631: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0099104: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0099437: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0099639: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0015724: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0074994: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0078113: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0077567: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0078791: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0078806: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0078936: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0078749: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0078880: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0078935: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0073604: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0073706: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0078871: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0078751: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080362: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080440: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080607: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0073537: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0075035: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080438: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080787: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0082537: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0082334: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0082025: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0081432: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0083146: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0082914: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0082379: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0083973: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0082841: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0083361: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0084678: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085233: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0073265: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0081366: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0084107: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085364: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085628: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085442: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0086176: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0086563: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0068958: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080583: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0086288: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0086849: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0087909: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0087798: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0089395: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0089850: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0088092: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0089993: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0088745: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0090057: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0090364: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085253: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0087319: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0089238: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0088959: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0090271: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0090644: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0089561: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0088828: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0093090: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0092863: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0092853: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0092254: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0089452: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0091192: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0094720: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0094271: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0094693: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0093523: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0093211: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0094997: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0096871: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0096830: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0095878: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0096954: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0097726: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0081203: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0082279: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0082285: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0087512: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0089409: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0088920: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0089857: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0089678: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0092632: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0092588: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0094709: 1406 (22001): Data too long for column 'screenwriter' at row 1\n",
      "Error insertando fila tt0109264: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0079258: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0079014: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0079579: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0079835: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0077648: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080541: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080563: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080376: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080591: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080883: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0082773: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0082361: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0081717: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0082601: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080693: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0081199: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0084151: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0084085: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0083547: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0083357: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085227: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085251: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085268: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085320: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085416: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0086030: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0086330: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0086868: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0086866: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0086854: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0088222: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0088952: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0089064: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0089976: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0089954: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0087084: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0088339: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0087301: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0089089: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0090565: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0090570: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0092294: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0092553: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0092559: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0093371: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0092604: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0092931: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0092903: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0094236: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0092131: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0094314: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0093944: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0096025: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0099027: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0100342: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0100303: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0100327: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0100457: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0099192: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0101953: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0101262: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0101499: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0102385: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0102448: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0103607: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0101996: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0078508: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0078805: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0078895: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0079145: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0078053: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0079181: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0079341: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0079706: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080608: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0080915: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0082504: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0082342: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0083906: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0083581: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0084158: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085528: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085627: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085645: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0085420: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0087882: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0086931: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0087942: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0087344: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0089923: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0088809: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0089499: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0089118: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0089972: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0090738: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0090765: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0092771: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0092966: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0094710: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0093662: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0094666: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0094857: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0099587: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0099577: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0097928: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0100111: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0101860: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0102000: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0101395: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0101759: 1054 (42S22): Unknown column 'nan' in 'field list'\n",
      "Error insertando fila tt0101736: 1054 (42S22): Unknown column 'nan' in 'field list'\n"
     ]
    }
   ],
   "source": [
    "import mysql.connector\n",
    "import pandas as pd\n",
    "\n",
    "# Conexión a la base de datos\n",
    "cnx = mysql.connector.connect(\n",
    "    user=\"root\",\n",
    "    password=\"AlumnaAdalab\",\n",
    "    host=\"127.0.0.1\",\n",
    "    database=\"CineParadiso\",\n",
    "    auth_plugin='mysql_native_password'\n",
    ")\n",
    "\n",
    "mycursor = cnx.cursor()\n",
    "\n",
    "# Leer el CSV donde tienes la información\n",
    "data_movies = pd.read_csv('FilmsCompleto.csv')\n",
    "\n",
    "# Reemplazar NaN con None para asegurar que los valores nulos se insertan correctamente\n",
    "data_movies = data_movies.where(pd.notnull(data_movies), None)\n",
    "\n",
    "# Verificar que el reemplazo se realizó correctamente\n",
    "print(data_movies.head())\n",
    "\n",
    "# Definir la consulta de inserción\n",
    "query = ('INSERT INTO Film (idOwner, title, type, year, genre, screenwriter, management, plot, length, rating) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)')\n",
    "\n",
    "# Convertir DataFrame a una lista de tuplas\n",
    "data_tuples = [tuple(x) for x in data_movies.to_numpy()]\n",
    "\n",
    "# Iterar sobre cada tupla e insertar en la base de datos\n",
    "for row in data_tuples:\n",
    "    try:\n",
    "        mycursor.execute(query, row)\n",
    "    except mysql.connector.Error as err:\n",
    "        print(f\"Error insertando fila {row[0]}: {err}\")\n",
    "\n",
    "# Confirmar los cambios en la base de datos\n",
    "cnx.commit()\n",
    "\n",
    "# Cerrar el cursor y la conexión\n",
    "mycursor.close()\n",
    "cnx.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "             Nombre                Nacimiento  \\\n",
      "0          Aldo Ray  25 de septiembre de 1926   \n",
      "1  William Marshall      19 de agosto de 1924   \n",
      "2      Terry Michos   26 de diciembre de 1953   \n",
      "3   Russell Johnson   10 de noviembre de 1924   \n",
      "4    Paul Tanashian       13 de marzo de 1960   \n",
      "\n",
      "                                             Premios Nominaciones  \\\n",
      "0  {'premios ganados': ['1979 Ganador AFAA Award'...         None   \n",
      "1                                               None         None   \n",
      "2                                               None         None   \n",
      "3  {'premios ganados': ['2007 Nominado TV Land Aw...         None   \n",
      "4                                               None         None   \n",
      "\n",
      "                                        Conocido por  \n",
      "0  ('No somos ángeles', 'La impetuosa', 'Nimh: El...  \n",
      "1  ('Drácula negro', 'Maverick', 'Grita Blácula g...  \n",
      "2  ('Los amos de la noche', 'El gran desafío en h...  \n",
      "3  ('La isla de Gílligan', 'Regreso a la Tierra',...  \n",
      "4  ('Furia oriental', 'El furor del dragón', 'Ope...  \n"
     ]
    }
   ],
   "source": [
    "import mysql.connector\n",
    "import pandas as pd\n",
    "\n",
    "# Conexión a la base de datos\n",
    "cnx = mysql.connector.connect(\n",
    "    user=\"root\",\n",
    "    password=\"AlumnaAdalab\",\n",
    "    host=\"127.0.0.1\",\n",
    "    database=\"CineParadiso\",\n",
    "    auth_plugin='mysql_native_password'\n",
    ")\n",
    "\n",
    "mycursor = cnx.cursor()\n",
    "\n",
    "# Leer el CSV donde tienes la información\n",
    "data_movies = pd.read_csv('tabla_actores.csv')\n",
    "\n",
    "# Reemplazar NaN con None para asegurar que los valores nulos se insertan correctamente\n",
    "data_movies = data_movies.where(pd.notnull(data_movies), None)\n",
    "\n",
    "# Verificar que el reemplazo se realizó correctamente\n",
    "print(data_movies.head())\n",
    "\n",
    "# Definir la consulta de inserción\n",
    "query = ('INSERT INTO Cast (name, birth, award, nomination, known_for) VALUES (%s,%s,%s,%s,%s)')\n",
    "\n",
    "# Convertir DataFrame a una lista de tuplas\n",
    "data_tuples = [tuple(x) for x in data_movies.to_numpy()]\n",
    "\n",
    "# Iterar sobre cada tupla e insertar en la base de datos\n",
    "for row in data_tuples:\n",
    "    try:\n",
    "        mycursor.execute(query, row)\n",
    "    except mysql.connector.Error as err:\n",
    "        print(f\"Error insertando fila {row[0]}: {err}\")\n",
    "\n",
    "# Confirmar los cambios en la base de datos\n",
    "cnx.commit()\n",
    "\n",
    "# Cerrar el cursor y la conexión\n",
    "mycursor.close()\n",
    "cnx.close()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
